# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoStreaming' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VideoStreaming

  target 'VideoStreamingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoStreamingUITests' do
    inherit! :search_paths
    # Pods for testing
  end
   pod 'GPUImage'
end
